services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - application-network

  backend:
    build: ./backend
    ports:
      - "3500:3500"
    environment:
      - DB_URL=${DB_URL}
    networks:
      - application-network
  
networks:
    application-network:
      driver: bridge
