services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3500/api/tasks
    depends_on:
      - backend
    networks:
      - application-network

  backend:
    build: ./backend
    ports:
      - "3500:3500"
    environment:
      - DB_URL="mongodb+srv://albertstephanie630:s8cqG55ry0pGFnZM@cluster0.b96rscx.mongodb.net/sweetness?retryWrites=true&w=majority&appName=Cluster0"
    networks:
      - application-network

  # mongo:
  #   image: mongo:6
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - application-network
  
networks:
    application-network:
      driver: bridge
