apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Stefanie-A/DevOps-Full-Stack-Project.git
    targetRevision: main
    path: ./Application-Code/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
