apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Deployment created by kubectl apply"
      labels:
        app: app-backend
    spec:
      containers:
        - name: app-backend
          image: 
          imagePullPolicy: IfNotPresent  # Always, Never, IfNotPresent
          ports:
            - containerPort: 3500
          env:
          - name: DB_CONN_STR
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_CONN_STR
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: db-secret
                key: DB_PASSWORD
  