apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: my-app
  labels:
    app: backend-service
spec:
  selector:
    app: app-backend
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
  type: ClusterIP
  sessionAffinity: None