apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: my-app
spec:
  selector:
    matchLabels:
      app: app-frontend
  replicas: 1
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Deployment created by kubectl apply"
      labels:
        app: app-frontend
    spec:
      containers:
        - name: app-frontend
          image: stefnie/app-frontend:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always  # Always, Never, IfNotPresent
      