name: cd pipeline
on:
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Configure AWS Credentials for OIDC
          uses: aws-actions/configure-aws-credentials@v4.1.0
          with:
            audience: sts.amazonaws.com
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::902839103466:role/openid-role

        - name: SSH into EC2 instance
          uses: appleboy/ssh-action@v0.1.9
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              echo "Deploying application..."